config/routes.rb
Omrails::Application.routes.draw do
  

  resources :networks

  get 'i/:id/:network_id' => 'tracker#impression'
  get 'v/:id/:network_id' => 'tracker#view'

  get 'videos/:id/embed(/:network_id)' => 'videos#embed', as: :embed
  resources :videos

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  root :to    => 'pages#home'

  get 'home'  => 'pages#home'
  get 'about' => 'pages#about'

end

app/models/network.rb
class Network < BaseModel
  attr_accessible :name

  validates_presence_of :name

  uniquify :token do
    generate_token
  end

  has_many :impressions, inverse_of: :network
  has_many :videos, through: :impressions


  # find by internal id or youtube video_id
  def self.find(id)
    if !id || "#{id}".numeric?
      return super id
    else
      return find_by_token id
    end
  end

  def videos
    super.group('videos.id')
  end

  def count_videos
    videos.count.count
  end

  # an impression occurs every time an embed iframe is loaded
  def impressions video=nil, o={}
    o[:unique] = true if o[:unique].nil?
    i = super()
    i = i.where(video_id: video.id) if video
    i = i.select('DISTINCT video_id, ip_address') if o[:unique]
    i
  end
  def count_impressions video=nil, o={}
    i = self.impressions video, o
    i.count
  end

  # plays occur when someone clicks the video in an embed
  #   to begin playing of the video
  def plays video=nil, o={}
    o[:min_state] = Play.default_min_state if o[:min_state].nil?
    o[:max_state] = Play.default_max_state if o[:max_state].nil?
    o[:min_state] = [o[:max_state], o[:min_state]].min
    i = self.impressions(video, o).joins(:play)
    i.where("state >= ? AND state <= ?", o[:min_state], o[:max_state])
  end
  def count_plays video=nil, o={}
    plays(video, o).count
  end

  # a view = total plays >= 25%, not unique
  def views video=nil
    plays video, unique: false
  end
  # count_views is what is used in CPM calculation
  def count_views video=nil
    views(video).count
  end


  def count_bounces video=nil
    count_plays(video, unique: false, max_state: 0)
  end

  # amount of money a network has made on vydia
  #   total of all network's video_revenue added up
  def revenue
    sum = 0
    videos.all.each do |v|
      sum += video_revenue(v)
    end
    sum
  end

  # amount of money a video has brought in for this network
  def video_revenue video, views = nil
    views ||= count_views(video)
    Network.cpm_formula(offered_cpm(video.cpm), views)
  end

  def vydia_revenue
    revenue / split_keep * vydia_keep
  end
  
  # CPM the network keeps
  def offered_cpm bid_cpm
    bid_cpm * split_keep
  end
  
  # CPM Vydia keeps
  def vydia_cpm bid_cpm
    bid_cpm * (1 - split_keep)
  end

  # define ratio ( 1 == network keeps 100% and Vydia keeps 0% )
  def split_keep
    Network.default_split
  end
  def vydia_keep
    (1 - split_keep)
  end

  # Class Methods
  def self.cpm_formula cpm, views
    views.to_f / Money.one_thousand * cpm
  end

  # calculate total Vydia revenue
  def self.vydia_revenue
    sum = 0
    Network.all.each do |n|
      r    = n.vydia_revenue
      sum += r
    end
    sum
  end
  
  # CPM the network keeps
  def self.offered_cpm bid_cpm
    bid_cpm.to_f * default_split
  end
  def self.default_split
    0.50
  end


  # generate a random token via uuid
  def self.generate_token
    # make sure the token has non-digit characters
    #   this prevents find(id) from getting confused
    begin
      token = SecureRandom.uuid.split('-').first
    end while token.numeric?
    token
  end


end

app/controllers/networks_controller.rb
class NetworksController < BaseAuthController
  # GET /networks
  # GET /networks.json
  def index
    @networks = Network.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @networks }
    end
  end

  # GET /networks/1
  # GET /networks/1.json
  def show
    @network  = Network.find(params[:id])

    @videos   = @network.videos

    @impressions = @network.impressions

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @network }
    end
  end

  # GET /networks/new
  # GET /networks/new.json
  def new
    @network = Network.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @network }
    end
  end

  # GET /networks/1/edit
  def edit
    @network = Network.find(params[:id])
  end

  # POST /networks
  # POST /networks.json
  def create
    @network = Network.new(params[:network])

    respond_to do |format|
      if @network.save
        format.html { redirect_to @network, notice: 'Network was successfully created.' }
        format.json { render json: @network, status: :created, location: @network }
      else
        format.html { render action: "new" }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /networks/1
  # PUT /networks/1.json
  def update
    @network = Network.find(params[:id])

    respond_to do |format|
      if @network.update_attributes(params[:network])
        format.html { redirect_to @network, notice: 'Network was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /networks/1
  # DELETE /networks/1.json
  def destroy
    @network = Network.find(params[:id])
    @network.destroy

    respond_to do |format|
      format.html { redirect_to networks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/networks_helper.rb
module NetworksHelper
  def link_to_network obj
    link_to obj.name, network_url(obj)
  end
end

app/views/networks/_form.html.erb
<%= simple_form_for(@network) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/networks/_networks.html.erb
<% unless @networks.blank? %>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th># Videos</th>
      <th>Network Token</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @networks.each do |network| %>
      <tr>
        <td><%= link_to_network network %></td>
        <td><%= network.count_videos %></td>
        <td><%= network.token%></td>
        <td><%= link_to icon_update, edit_network_path(network) %></td>
        <td><%= link_to icon_destroy, network, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
  </tbody>

</table>



<% else %>

<h5>no networks</h5>

<% end %>

app/views/networks/_videos.html.erb
<% unless @videos.blank? %>
  <table class="table datatable">
    <thead>
      <tr>
        <th>Video</th>
        <th>Offered CPM</th>
        <th>Unique Impressions</th>
        <th>Impressions</th>
        <th>Unique Views</th>
        <th>Views</th>
        <th>Full Plays</th>
        <th>Bounces</th>
        <th>Revenue</th>
      </tr>
    </thead>

    <tbody>
      <%  totals = {
            offered_cpm: 0,
            unique_impressions: 0,
            impressions: 0,
            unique_views: 0,
            views: 0,
            full_plays: 0,
            bounces: 0,
            royalties: 0
          }
      %>
      <% @videos.each do |v| %>

        <% offered_cpm = @network.offered_cpm(v.cpm) %>
        <% totals[:offered_cpm] += offered_cpm %>

        <% unique_impressions = @network.count_impressions(v, unique: true) %>
        <% totals[:unique_impressions]  += unique_impressions %>

        <% impressions = @network.count_impressions(v, unique: false) %>
        <% totals[:impressions] += impressions %>

        <% unique_views = @network.count_plays(v, unique: true) %>
        <% totals[:unique_views]  += unique_views %>

        <% views = @network.count_views(v) %>
        <% totals[:views] += views %>

        <% full_plays = @network.count_plays(v, unique: false, min_state: 4) %>
        <% totals[:full_plays]  += full_plays %>
        
        <% bounces = @network.count_plays(v, unique: false, max_state: 0) %>
        <% totals[:bounces] += bounces %>
        
        <% royalties = @network.video_revenue(v, views) %>
        <% totals[:royalties] += royalties %>


        <tr>
          <!-- Video Name -->
          <td><%= link_to_video v %></td>

          <!-- Video Offered CPM -->
          <td><%= Money.new(offered_cpm).with_symbol %></td>

          <!-- Unique Impressions -->
          <td><%= unique_impressions %></td>

          <!-- Impressions -->
          <td><%= impressions %></td>

          <!-- Unique Views -->
          <td><%= unique_views %></td>

          <!-- Views -->
          <td><%= views %></td>

          <!-- Full Plays -->
          <td><%= full_plays %></td>

          <!-- Bounces -->
          <td><%= bounces %></td>

          <!-- Royalties Collected from Video -->
          <td><%= Money.new(royalties).with_symbol %></td>
        </tr>
      <% end %>
    </tbody>


    <tfoot>
      <tr class="totals">
        <!-- Video Name -->
        <th>Totals</th>

        <!-- Video Offered CPM -->
        <th><%= Money.new(totals[:offered_cpm]).with_symbol %></th>

        <!-- Unique Impressions -->
        <th><%= totals[:unique_impressions] %></th>

        <!-- Impressions -->
        <th><%= totals[:impressions] %></th>

        <!-- Unique Views -->
        <th><%= totals[:unique_views] %></th>

        <!-- Views -->
        <th><%= totals[:views] %></th>

        <!-- Full Plays -->
        <th><%= totals[:full_plays] %></th>

        <!-- Bounces -->
        <th><%= totals[:bounces] %></th>

        <!-- Royalties Collected from Video -->
        <th><%= Money.new(totals[:royalties]).with_symbol %></th>
      </tr>


    </tfoot>


  </table>

<script type="text/javascript">
  // $('.datatable').dataTable({
  //   "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
  //   "sPaginationType": "bootstrap",

  //   "fnFooterCallback": function ( nRow, aaData, iStart, iEnd, aiDisplay ) {
      /*
       * Calculate the total market share for all browsers in this table (ie inc. outside
       * the pagination)
       */
      // var l = aaData.length;
      // var full_totals = new Array(l).join('0').split('').map(parseFloat);

      // console.log("aaData",aaData);

      // for ( var i=0 ; i<l ; i++ ){

      //   var row = aaData[i];
      //   var ll  = row.length;
      //   for( var ii=0 ; ii<ll ; ii++ ){
      //     full_totals[ii] += row[ii];
      //   }
      // }
      
      // console.log("full_totals",full_totals);

      /* Calculate the market share for browsers on this page */
      // var page_totals = [];
      // for ( var i=iStart ; i<iEnd ; i++ ){
      //   iPageMarket += aaData[ aiDisplay[i] ][4]*1;
      // }
      
      /* Modify the footer row to match what we want */
      // var nCells = nRow.getElementsByTagName('th');
      // nCells[1].innerHTML = parseInt(iPageMarket * 100)/100 +
      //   '% ('+ parseInt(iTotalMarket * 100)/100 +'% total)';
  //   }
  // });
</script>

<% else %>
  <p>This network has no video features</p>
<% end %>

app/views/networks/edit.html.erb
<h1>Editing network</h1>

<%= render 'form' %>

<%= link_to 'Show', @network %> |
<%= link_to 'Back', networks_path %>

app/views/networks/index.html.erb
<h1>Listing networks</h1>

<%= render 'networks' %>

<br />

<%= link_to 'New Network', new_network_path %>

app/views/networks/new.html.erb
<h1>New network</h1>

<%= render 'form' %>

<%= link_to 'Back', networks_path %>

app/views/networks/show.html.erb
<h2><%= @network.name %></h2>

<p>
  <b>Token:</b>
  <%= @network.token %>
</p>

<h3>Features:</h3>
<%= render 'videos' %>


<%= link_to 'Edit', edit_network_path(@network) %> |
<%= link_to 'Back', networks_path %>