config/routes.rb
Omrails::Application.routes.draw do
  

  resources :networks

  get 'i/:id/:network_id' => 'tracker#impression'
  get 'v/:id/:network_id' => 'tracker#view'

  get 'videos/:id/embed(/:network_id)' => 'videos#embed', as: :embed
  resources :videos

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  root :to    => 'pages#home'

  get 'home'  => 'pages#home'
  get 'about' => 'pages#about'

end

app/views/layouts/_footer.html.erb
<div class="footer">
<!-- 
	<small>
		<%= link_to "trendsetter", "http://trendsettermarketing.net" %>
	</small>
   -->
</div>

app/views/layouts/_head.html.erb
<head>
	<title><%= @title || "Vydia Ad Network" %></title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=4, user-scalable=yes" />
</head>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%=link_to "Vydia Ad Network", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
          <% if user_signed_in? %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
          <% end %>
        </ul>

        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to "Videos", videos_path %>
            </li>
            <li>
              <%= link_to "Networks", networks_path %>
            </li>
            <!-- <li>
              <%= link_to "Edit Profile", edit_user_registration_path %>
            </li> -->
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "Login", new_user_session_path %>
            </li>
          <% end %>
        </ul>
        
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/app_embed.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @video.name %></title>
		<%= stylesheet_link_tag    "app_embed", :media => "all" %>
		<%= javascript_include_tag "app_embed" %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
	</head>
	<body class="<%= @video.ad_bottom.blank? ? "" : "with-ad" %>">
		
		<%= yield %>

		<%= tracking_pixel @video, @network, :impression %>

	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	
	<%= render "layouts/head" %>

	<body>

		<%= render "layouts/header" %>

		<div class="container">

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class:"alert alert-#{name}") %>
		<% end %>

		<%= yield %>

		<%= render "layouts/footer" %>
		</div>

	</body>
</html>

app/views/layouts/embed_error.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Error</title>
		<%= stylesheet_link_tag    "embed_error", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
	</head>
	<body>
		<div class="error-container">
			<%= yield %>
		</div>

	</body>
</html>